import { reverseObject } from 'src/lib/utils';

const PacketRequestCode = {
  START_PRINT: 1,
  START_PAGE_PRINT: 3,
  SET_DIMENSION: 19,
  GET_RFID: 26,
  SET_LABEL_DENSITY: 33,
  SET_LABEL_TYPE: 35,
  GET_INFO: 64,
  IMAGE_DATA_META: 132,
  IMAGE_DATA: 133,
  GET_PRINT_STATUS: 163,
  GET_HEART_BEAT: 220,
  END_PAGE_PRINT: 227,
  END_PRINT: 243,
};

const PacketResponseCode = {
  START_PRINT: 2,
  START_PAGE_PRINT: 4,
  SET_DIMENSION: 20,
  GET_RFID: 27,
  SET_LABEL_DENSITY: 49,
  SET_LABEL_TYPE: 51,
  GET_INFO_DENSITY: 65,
  GET_INFO_PRINT_SPEED: 66,
  GET_INFO_LABEL_TYPE: 67,
  GET_INFO_LANGUAGE_TYPE: 70,
  GET_INFO_AUTO_SHUTDOWN_TIME: 71,
  GET_INFO_DEVICE_TYPE: 72,
  GET_INFO_SOFTWARE_VERSION: 73,
  GET_INFO_BATTERY: 74,
  GET_INFO_DEVICE_SERIAL: 75,
  GET_INFO_HARDWARE_VERSION: 76,
  GET_PRINT_STATUS: 179,
  GET_HEART_BEAT: 217,
  END_PAGE_PRINT: 228,
  END_PRINT: 244,
};

export const PacketCode = {
  ...reverseObject(PacketRequestCode),
  ...reverseObject(PacketResponseCode),
};
